inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - spec/fixtures/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
